### ISSUE TITLE
Is there any exaples how to do reponse to api tg? 

### ISSUE THREAD

**Issue by Morvine78** [klev-o/telegram-bot-api#10]
intereseting in getChatMember reponse and have no idea how to do this.
i've found that there i need user_id and chat_id (i can get it from update->message)
then i should send it to https://api.telegram.org/botTOKEM/getChatMember and resive status.
if you could tell me where can i reed this please

**Comment by Morvine78** [comment]
if platform allows to use russian language it will better to talk this way

**Comment by klev-o** [comment]
Не совсем понял, в чем именно проблема)
Но допустим, у нас есть какой-то чат, в нем несколько участников. С помощью метода getChatMember (подробное описание - https://core.telegram.org/bots/api#getchatmember)  можно проверить информацию о конкретном участнике. 

В сам метод нам нужно передать объект GetChatMember с указанными ID чата и ID запрашиваемого пользователя.

Это может выглядеть так:

`use Klev\TelegramBotApi\Telegram;`
`use Klev\TelegramBotApi\Methods\GetChatMember;`

`$bot = new Telegram('your personal token');`
`$result = $bot->getChatMember(new GetChatMember('-12345678901234', 987654321));`

Ответ от данного метода может выглядеть так:

`Klev\\TelegramBotApi\\Types\\ChatMemberOwner: {"status":"creator","is_anonymous":false,"custom_title":null,"user":{"id":987654321,"is_bot":false,"first_name":"User name","last_name":null,"username":"username","language_code":"ru","is_premium":true,"added_to_attachment_menu":null,"can_join_groups":null,"can_read_all_group_messages":null,"supports_inline_queries":null}}`

Таким образом мы получим определенный объект с результатом. Общий класс ответа будет ChatMember, а более конкретный тип будет зависеть от того, какой у запрашиваемого пользователя будет статус. На данный момент, согласно официальному апи, могут быть следующие варианты: ChatMemberOwner, ChatMemberAdministrator, ChatMemberMember, ChatMemberRestricted, ChatMemberLeft, ChatMemberBanned. Более подробно об этом сказано здесь - https://core.telegram.org/bots/api#chatmember

**Comment by Morvine78** [comment]
Огромное спасибо) 
Именно вызов самого метода был не понятен)
