### ISSUE TITLE
editMessageReplyMarkup calls the `request` method with an incorrect value

### ISSUE THREAD

**Issue by nabeghe** [klev-o/telegram-bot-api#14]
Hi. The `editMessageReplyMarkup ` method in the Telegram class calls the `request` method with incorrect value `editMessageText`, which is a typo. It should pass `editMessageReplyMarkup`.

**Comment by klev-o** [comment]
Hello! That's right, there really is a typo, thanks for the feedback!

I will fix it in the next update. In the meantime, you can use the "makeRequest" method, good luck!

**Comment by klev-o** [comment]
Hi there! The typo was fixed in the latest release.
