### ISSUE TITLE
Send message to all groups where bot is member

### ISSUE THREAD

**Issue by adalenv** [klev-o/telegram-bot-api#15]
It's there any method to send message to all groups where bot is member.
I was thinking to save chat id every time bot added to a group but I'm looking if it's any built in feature?

**Comment by klev-o** [comment]
Hi! As far as I know, there is no built-in function for this. Therefore, you can save chat identifiers, and then loop through them and send messages.
You also need to take into account chat permissions, rights for the bot that are set in the chat, etc. - there may be restrictions on its operation

**Comment by klev-o** [comment]
OK

**Comment by adalenv** [comment]
thank you😀
