### ISSUE TITLE
request_contact within keyboard not possible

### ISSUE THREAD

**Issue by justcode049** [klev-o/telegram-bot-api#17]
i am trying to use reuest_contact within a keyboard, but i can't get it to work

$button = new InlineKeyboardButton([
        'text' => 'Teile bitte deine Telefonnummer zur Authentifizierung',
        'request_contact' => true
    ]);
    $keyboard = [[ $button ]];
    $replyMarkup = new InlineKeyboardMarkup([
        'inline_keyboard' => $keyboard
    ]);

**Comment by klev-o** [comment]
Hello! Unfortunately, the request_button option is only available for the regular keyboard, not the inline_keyboard (According to the documentation https://core.telegram.org/bots/api#keyboardbutton)
Therefore, you can use code like this:

```
$button = new \Klev\TelegramBotApi\Types\KeyboardButton('Teile bitte deine Telefonnummer zur Authentifizierung', true);
$replyMarkup = new \Klev\TelegramBotApi\Types\ReplyKeyboardMarkup();
$replyMarkup->keyboard = [[ $button ]];
```
