### ISSUE TITLE
how can i get the id of a person who enters in a channel?

### ISSUE THREAD

**Issue by TravisScottex** [klev-o/telegram-bot-api#6]
how can i get the id of a person who enters in a channel via an invitation link? $update->message->new_chat_members doesn't work

**Comment by klev-o** [comment]
Added this feature in version 1.3.0 - according to the official documentation "Added the ability to process join requests that were created without an invite link. Bots will receive the 'chat_join_request' update as usual."
It follows from this that you can get the id in an advising way: $update->chat_join_request->from->id
